# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/ef44/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/pantech/ef44/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so

PRODUCT_COPY_FILES += \
  vendor/pantech/ef44/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
  vendor/pantech/ef44/proprietary/bin/mpdecision:system/bin/mpdecision \
  vendor/pantech/ef44/proprietary/bin/netmgrd:system/bin/netmgrd \
  vendor/pantech/ef44/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/pantech/ef44/proprietary/bin/qmuxd:system/bin/qmuxd \
  vendor/pantech/ef44/proprietary/bin/thermald:system/bin/thermald \
  vendor/pantech/ef44/proprietary/bin/time_daemon:system/bin/time_daemon \
  vendor/pantech/ef44/proprietary/bin/cnd:system/bin/cnd \
  vendor/pantech/ef44/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
  vendor/pantech/ef44/proprietary/bin/port-bridge:system/bin/port-bridge \
  vendor/pantech/ef44/proprietary/bin/qmiproxy:system/bin/qmiproxy \
  vendor/pantech/ef44/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
  vendor/pantech/ef44/proprietary/bin/quipc_igsn:system/bin/quipc_igsn \
  vendor/pantech/ef44/proprietary/bin/quipc_main:system/bin/quipc_main \
  vendor/pantech/ef44/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
  vendor/pantech/ef44/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
  vendor/pantech/ef44/proprietary/bin/rild:system/bin/rild \
  vendor/pantech/ef44/proprietary/bin/gsiff_daemon:system/bin/gsiff_daemon \
  vendor/pantech/ef44/proprietary/bin/qseecomd:system/bin/qseecomd \
  vendor/pantech/ef44/proprietary/bin/pantech_server:system/bin/pantech_server \
  vendor/pantech/ef44/proprietary/bin/usb_manager:system/bin/usb_manager \
  vendor/pantech/ef44/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
  vendor/pantech/ef44/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_ov2720_hfr.so:system/lib/libchromatix_ov2720_hfr.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_ov2720_zsl.so:system/lib/libchromatix_ov2720_zsl.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_ov5647_default_video.so:system/lib/libchromatix_ov5647_default_video.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_ov5647_video_hfr.so:system/lib/libchromatix_ov5647_video_hfr.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_ov8825_default_video.so:system/lib/libchromatix_ov8825_default_video.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_ov8825_preview.so:system/lib/libchromatix_ov8825_preview.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_ov9726_default_video.so:system/lib/libchromatix_ov9726_default_video.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_ov9726_preview.so:system/lib/libchromatix_ov9726_preview.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
  vendor/pantech/ef44/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
  vendor/pantech/ef44/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
  vendor/pantech/ef44/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
  vendor/pantech/ef44/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/pantech/ef44/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
  vendor/pantech/ef44/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
  vendor/pantech/ef44/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
  vendor/pantech/ef44/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
  vendor/pantech/ef44/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
  vendor/pantech/ef44/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
  vendor/pantech/ef44/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
  vendor/pantech/ef44/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/pantech/ef44/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/pantech/ef44/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/pantech/ef44/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
  vendor/pantech/ef44/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
  vendor/pantech/ef44/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
  vendor/pantech/ef44/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
  vendor/pantech/ef44/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
  vendor/pantech/ef44/proprietary/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
  vendor/pantech/ef44/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
  vendor/pantech/ef44/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
  vendor/pantech/ef44/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/pantech/ef44/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/pantech/ef44/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
  vendor/pantech/ef44/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/pantech/ef44/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/pantech/ef44/proprietary/lib/libqdi.so:system/lib/libqdi.so \
  vendor/pantech/ef44/proprietary/lib/libqdp.so:system/lib/libqdp.so \
  vendor/pantech/ef44/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/pantech/ef44/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
  vendor/pantech/ef44/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
  vendor/pantech/ef44/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
  vendor/pantech/ef44/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
  vendor/pantech/ef44/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
  vendor/pantech/ef44/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
  vendor/pantech/ef44/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
  vendor/pantech/ef44/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
  vendor/pantech/ef44/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
  vendor/pantech/ef44/proprietary/lib/libril.so:system/lib/libril.so \
  vendor/pantech/ef44/proprietary/lib/libsyslog.so:system/lib/libsyslog.so \
  vendor/pantech/ef44/proprietary/lib/libsky_rawdata.so:system/lib/libsky_rawdata.so \
  vendor/pantech/ef44/proprietary/lib/libskytestclient.so:system/lib/libskytestclient.so \
  vendor/pantech/ef44/proprietary/lib/libpantech_qcci.so:system/lib/libpantech_qcci.so \
  vendor/pantech/ef44/proprietary/lib/libpantech_wifi_mac_backup.so:system/lib/libpantech_wifi_mac_backup.so \
  vendor/pantech/ef44/proprietary/lib/libpantech_wifi_mac_rw.so:system/lib/libpantech_wifi_mac_rw.so \
  vendor/pantech/ef44/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
  vendor/pantech/ef44/proprietary/lib/libcneapiclient.so:system/lib/libcneapiclient.so \
  vendor/pantech/ef44/proprietary/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
  vendor/pantech/ef44/proprietary/lib/libcneutils.so:system/lib/libcneutils.so \
  vendor/pantech/ef44/proprietary/lib/libxml.so:system/lib/libxml.so \
  vendor/pantech/ef44/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
  vendor/pantech/ef44/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
  vendor/pantech/ef44/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
  vendor/pantech/ef44/proprietary/lib/libyas530.so:system/lib/libyas530.so \
  vendor/pantech/ef44/proprietary/lib/hw/lights.msm8960.so:system/lib/hw/lights.msm8960.so \
  vendor/pantech/ef44/proprietary/bin/BCM4334B0_002.001.013.0360.0458_RC.hcd:system/bin/BCM4334B0_002.001.013.0360.0458_RC.hcd \
  vendor/pantech/ef44/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so
